# Generated by Django 5.1 on 2024-08-31 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="recipe",
        ),
        migrations.AddField(
            model_name="recipe",
            name="dish",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="planning.dish",
            ),
            preserve_default=False,
        ),
    ]
