# Generated by Django 5.1 on 2024-10-18 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="day",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meals",
                to="planning.day",
            ),
        ),
    ]
