# Generated by Django 5.1 on 2024-09-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0002_remove_recipe_recipe_recipe_dish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeproduct",
            name="unit",
            field=models.CharField(
                choices=[("броя", "броя"), ("гр.", "гр.")], default="гр.", max_length=20
            ),
        ),
    ]
