# Generated by Django 5.1 on 2024-09-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0002_product_calories_per_100g"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="calories_per_100g",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
