# Generated by Django 5.1 on 2024-08-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0002_dish_description_alter_dish_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(default="Recipe description"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
